#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
'''
@File    :   mobilome_nhmmer_tblout2bed
@Time    :   2022/03/21 13:50:16
@Author  :   Naisu Yang 
@Version :   1.0
@Contact :   3298990@qq.com
'''

# here put the import lib
import os
import sys
import time
import argparse

def main():
    parser = argparse.ArgumentParser( description='将blast结果文件格式6转换成bed格式')
    parser.add_argument('-t', '--tabular_file', type=str, required=True, help='tabular output formats 6' )
    parser.add_argument('-o', '--output_file', type=str, required=True, help='输出文件名' )
    args = parser.parse_args()
    with open(args.tabular_file) as handle1,open(args.output_file,'w') as handle2:
        for line in handle1:
            if not line.startswith('#'):
                chrom = line.split()[1]
                chromStart = int(line.split()[8])
                chromEnd = int(line.split()[9])
                if chromStart > chromEnd :
                    newline = f'{chrom}\t{chromEnd - 1}\t{chromStart}\t.\t.\t-\n'
                else:
                    newline = f'{chrom}\t{chromStart - 1}\t{chromEnd}\t.\t.\t+\n'
                handle2.write(newline)
            #bed 格式
            #chrom chromStart chromEnd name score strand
            #if line.split()[12]:

if __name__ == '__main__':
    main()
